/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#E8EEF3',
                    100: '#C5D4DE',
                    200: '#9FB8C9',
                    300: '#789BB4',
                    400: '#5B85A3',
                    500: '#3E6F92',
                    600: '#1B4F72',
                    700: '#163D59',
                    800: '#112E44',
                    900: '#0D2A3E',
                },
                gold: {
                    300: '#E3C96A',
                    400: '#D9B94E',
                    500: '#C9A843',
                    600: '#B08C30',
                    700: '#8C6E22',
                },
                success: {
                    400: '#34D399',
                    500: '#10B981',
                    600: '#059669',
                },
                danger: {
                    400: '#F87171',
                    500: '#EF4444',
                    600: '#DC2626',
                },
                dark: {
                    bg: '#0F172A',
                    card: '#1E293B',
                    border: '#334155',
                    text: '#94A3B8',
                },
                brand: {
                    "surface-variant": "#1c374c",
                    "surface-container-high": "#102c40",
                    "primary-fixed": "#ffe08a",
                    "secondary-fixed": "#d0e5fa",
                    "inverse-on-surface": "#173347",
                    "surface-container-low": "#001e31",
                    "surface-bright": "#213c50",
                    "tertiary-fixed-dim": "#b3c9e3",
                    "on-tertiary-fixed": "#051d31",
                    "on-secondary-fixed-variant": "#354959",
                    "surface-container-lowest": "#00101c",
                    "surface-dim": "#001524",
                    "on-tertiary": "#1d3247",
                    "background": "#001524",
                    "secondary": "#b4c9dd",
                    "primary": "#e6c35b",
                    "surface-container": "#032235",
                    "primary-container": "#c9a843",
                    "tertiary-container": "#98adc7",
                    "on-secondary-container": "#a6bbcf",
                    "tertiary-fixed": "#cfe5ff",
                    "on-tertiary-container": "#2c4156",
                    "error": "#ffb4ab",
                    "surface-container-highest": "#1c374c",
                    "surface-tint": "#e6c35b",
                    "on-secondary": "#1e3242",
                    "inverse-surface": "#cce5ff",
                    "outline": "#99907d",
                    "on-surface": "#cce5ff",
                    "secondary-fixed-dim": "#b4c9dd",
                    "secondary-container": "#374b5c",
                    "on-primary": "#3d2f00",
                    "on-surface-variant": "#d0c5b1",
                    "on-error": "#690005",
                    "surface": "#001524",
                    "primary-fixed-dim": "#e6c35b",
                    "on-background": "#cce5ff",
                    "error-container": "#93000a",
                    "tertiary": "#b3c9e3",
                    "on-tertiary-fixed-variant": "#34485e",
                    "on-primary-fixed-variant": "#574400",
                    "on-error-container": "#ffdad6",
                    "outline-variant": "#4d4637",
                    "inverse-primary": "#745b00",
                    "on-secondary-fixed": "#071d2c",
                    "on-primary-fixed": "#241a00",
                    "on-primary-container": "#4f3d00"
                }
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
            },
            animation: {
                'fade-in': 'fadeIn 0.6s ease-out',
                'slide-up': 'slideUp 0.6s ease-out',
                'float': 'float 6s ease-in-out infinite',
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { opacity: '0', transform: 'translateY(20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                float: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-20px)' },
                },
            },
            backdropBlur: {
                xs: '2px',
            },
        },
    },
    plugins: [],
}
